<?php

namespace TelegramNotifier\TelegramChain\TelegramCommands;


use TelegramNotifier\TelegramChain\TelegramCommandsParser;

class Search extends TelegramCommandsParser
{
    public function parse(string $command)
    {
        if ($this->canHandleCommand($command)) {
            print('Command: search');
        } else {
            parent::parse($command); // TODO: Change the autogenerated stub
        }
    }
}