<?php
/**
 * Created by PhpStorm.
 * User: stosdima
 * Date: 18.12.17
 * Time: 6:44
 */

namespace TelegramNotifier\TelegramChain\Commands;


class Admin extends Command
{
    protected $name = 'admin';

    protected $description = ' Welcome to admin-panel!';

    public function handle($closure)
    {
        if ($closure()->getMessage()->getText() == '/admin') {
            $chatId = $closure()->getMessage()->getChat()->getId();
            $this->api->sendMessage($chatId, $this->getDecription());
        }
    }

    public function make($api, $closure)
    {
        return parent::make($api, $closure); // TODO: Change the autogenerated stub
    }
}