<?php
/**
 * Created by PhpStorm.
 * User: stosdima
 * Date: 18.12.17
 * Time: 18:23
 */

namespace TelegramNotifier\TelegramChain\Commands;


use TelegramBot\Api\BotApi;
use TelegramNotifier\Helper;
use TelegramNotifier\TelegramDb;

class Admin extends Command
{
    protected $name = '/admin';

    protected $description = ' Welcome to admin-panel!';

    public function handle($data)
    {
        if (Helper::isLongPolling($data, $this->api, BotApi::class)) {
            if ($data->getMessage()->getText() == $this->getName()) {
                $chatId = $data->getMessage()->getChat()->getId();
                TelegramDb::updateStatus($chatId, 'admin');
                $this->api->sendMessage($chatId, $this->getDecription());
            }
        } else {
            $bot = $this->api;
            $bot->command($this->getName(), function ($message) use ($bot) {
                $chatId = $message->getChat()->getId();
                TelegramDb::updateStatus($chatId, 'admin');
                $bot->sendMessage($chatId, $this->getDecription());
            });
        }
    }

    public function make($api, $data)
    {
        return parent::make($api, $data); // TODO: Change the autogenerated stub
    }
}