<?php
/**
 * Created by PhpStorm.
 * User: stosdima
 * Date: 18.12.17
 * Time: 6:24
 */

namespace TelegramNotifier\TelegramChain\Commands;


use TelegramBot\Api\BotApi;
use TelegramNotifier\Helper;

class Help extends Command
{
    protected $name = '/help';

    protected $description =
        'List of commands:
        /start - start work with bot 
        /stop - stop work with bot
        /search - search posts by categories
        /admin - site administrator panel';

    public function handle($data)
    {
        if (Helper::isLongPolling($data, $this->api, BotApi::class)) {
            if ($data->getMessage()->getText() == $this->getName()) {
                $chatId = $data->getMessage()->getChat()->getId();
                $this->api->sendMessage($chatId, $this->getDecription());
            }
        } else {
            $bot = $this->api;
            $bot->command($this->getName(), function ($message) use ($bot) {
                $bot->sendMessage($message->getChat()->getId(), $this->getDecription());
            });
        }
    }

    public function make($api, $data)
    {
        return parent::make($api, $data); // TODO: Change the autogenerated stub
    }
}