<?php
/**
 * Created by PhpStorm.
 * User: stosdima
 * Date: 18.12.17
 * Time: 6:24
 */

namespace TelegramNotifier\TelegramChain\Commands;


class Help extends Command
{
    protected $name = 'help';

    protected $description =
        'List of commands:
        /start - start work with bot 
        /stop - stop work with bot
        /search - search posts by categories
        /admin - site administrator panel';

    public function handle($closure)
    {
        if ($closure()->getMessage()->getText() == '/help') {
            $chatId = $closure()->getMessage()->getChat()->getId();
            $this->api->sendMessage($chatId, $this->getDecription());
        }
    }

    public function make($api, $closure)
    {
        return parent::make($api, $closure); // TODO: Change the autogenerated stub
    }
}