<?php
/**
 * Created by PhpStorm.
 * User: stosdima
 * Date: 14.12.17
 * Time: 18:29
 */

namespace TelegramNotifier\TelegramChain\Commands;


use TelegramNotifier\TelegramDb;

class Search extends Command
{
    protected $name = 'search';

    protected $description = 'Search by: ';

    public function handle($closure)
    {
        $keyboard = new \TelegramBot\Api\Types\Inline\InlineKeyboardMarkup(
            [
                [
                    ['text' => 'Categories', 'callback_data' => 'categories'],
                    ['text' => 'Keyword', 'callback_data' => 'search-keyword'],
                ]
            ]
        );
        if ($closure()->getMessage()->getText() == '/search') {
            $chatId = $closure()->getMessage()->getChat()->getId();
            TelegramDb::updateStatus($chatId, 'search-keyword');
            $this->api->sendMessage($chatId, $this->getDecription(), 'html', false, null, $keyboard);
        }
    }

    public function make($api, $closure)
    {
        return parent::make($api, $closure); // TODO: Change the autogenerated stub
    }
}