<?php
/**
 * Created by PhpStorm.
 * User: stosdima
 * Date: 18.12.17
 * Time: 1:14
 */

namespace TelegramNotifier\TelegramChain\Commands;


use TelegramBot\Api\BotApi;
use TelegramNotifier\Helper;
use TelegramNotifier\TelegramDb;

class Start extends Command
{
    protected $name = '/start';

    protected $description = 'Hello, thank`s for subscribing. Commands list: /help';

    public function handle($closure)
    {
        if (Helper::isLongPolling($closure, $this->api, BotApi::class)) {
            if ($closure()->getMessage()->getText() == $this->getName()) {
                $chatId = $closure()->getMessage()->getChat()->getId();
                TelegramDb::addContact($chatId);
                $this->api->sendMessage($chatId, $this->getDecription());
            }
        }else {
            $bot = $this->api;
            $bot->command($this->getName(), function ($message) use ($bot){
                $bot->sendMessage($message->getChat()->getId(), $this->getDecription());
            });
        }
    }

    public function make($api, $closure)
    {
        return parent::make($api, $closure); // TODO: Change the autogenerated stub
    }
}