<?php
/**
 * Created by PhpStorm.
 * User: stosdima
 * Date: 18.12.17
 * Time: 6:45
 */

namespace TelegramNotifier\TelegramChain\Commands;


use TelegramNotifier\TelegramDb;

class Stop extends Command
{
    protected $name = 'stop';

    protected $description = 'You have been deleted from bot database. If you want start again, please, send me /start';


    public function handle($closure)
    {
        if ($closure()->getMessage()->getText() == '/stop') {
            $chatId = $closure()->getMessage()->getChat()->getId();
            TelegramDb::deleteContact($chatId);
            $this->api->sendMessage($chatId, $this->getDecription());
        }
    }

    public function make($api, $closure)
    {
        return parent::make($api, $closure); // TODO: Change the autogenerated stub
    }
}