<?php
/**
 * Created by PhpStorm.
 * User: stosdima
 * Date: 20.12.17
 * Time: 4:43
 */

namespace TelegramNotifier\TelegramChain\CallbackqueryCommands;


use TelegramNotifier\TelegramChain\Command;
use TelegramNotifier\TelegramDb;

class CreatePost extends Command
{
    protected $name = 'post-create';

    protected $description = 'Send me, please, your post <b>data( example - TITLE :: BODY)</b>: ';

    public function handle($data)
    {
        $callbackId = $data->getCallbackQuery()->getMessage()->getChat()->getId();
        if ($data->getCallbackQuery()->getData() == $this->getName()) {
            TelegramDb::updateStatus($callbackId, 'admin-post');
            $this->getApi()->sendMessage($callbackId, $this->getDecription(), 'html');
        }
    }

    public function make($api, $data)
    {
        return parent::make($api, $data); // TODO: Change the autogenerated stub
    }
}