<?php
/**
 * Created by PhpStorm.
 * User: stosdima
 * Date: 20.12.17
 * Time: 4:54
 */

namespace TelegramNotifier\TelegramChain\CallbackqueryCommands;


use TelegramNotifier\Helper;
use TelegramNotifier\TelegramChain\Command;
use TelegramNotifier\TelegramDb;

class DeletePost extends Command
{
    protected $name = 'post-delete';

    public function handle($data)
    {
        $callbackId = $data->getCallbackQuery()->getMessage()->getChat()->getId();
        if ($data->getCallbackQuery()->getData() == $this->getName()) {
            if (Helper::getPostsIfExist()) {
                $text = 'Please choose post ID which you want to delete from list below: ' . "\n";
                foreach (Helper::getPostsIfExist() as $post) {
                    $text .= Helper::generate_telegram_post(get_permalink($post->ID), $post->post_title,
                            'ID -> ' . $post->ID) . "\n";
                }
                TelegramDb::updateStatus($callbackId, 'admin-post-delete');
                $this->getApi()->sendMessage($callbackId, $text, 'html');
            } else {
                $text = 'You havent created posts :(';
                TelegramDb::resetStatus($callbackId);
                $this->getApi()->sendMessage($callbackId, $text);
            }
        }
    }

    public function make($api, $data)
    {
        return parent::make($api, $data); // TODO: Change the autogenerated stub
    }
}
