<?php
/**
 * Created by PhpStorm.
 * User: stosdima
 * Date: 20.12.17
 * Time: 4:27
 */

namespace TelegramNotifier\TelegramChain\CallbackqueryCommands;


use TelegramNotifier\TelegramChain\Command;
use TelegramNotifier\TelegramDb;

class Login extends Command
{
    protected $name = 'login';

    protected $description = 'Insert <b>verification code</b> from your site: ';

    public function handle($data)
    {
        $chatId = $data->getCallbackQuery()->getMessage()->getChat()->getId();
        if ($data->getCallbackQuery()->getData() == $this->getName()) {
            TelegramDb::updateStatus($chatId, 'admin-verif');
            $this->getApi()->sendMessage($chatId, $this->getDecription(), 'html');
        }
    }

    public function make($api, $data)
    {
        return parent::make($api, $data); // TODO: Change the autogenerated stub
    }
}