<?php
/**
 * Created by PhpStorm.
 * User: stosdima
 * Date: 20.12.17
 * Time: 4:48
 */

namespace TelegramNotifier\TelegramChain\CallbackqueryCommands;


use TelegramNotifier\TelegramChain\Command;
use TelegramNotifier\TelegramDb;

class SearchByKeyword extends Command
{
    protected $name = 'search-keyword';

    protected $description = 'Please, type <b>keyword</b> and you will get list of posts:';

    public function handle($data)
    {
        $callbackId = $data->getCallbackQuery()->getMessage()->getChat()->getId();
        if ($data->getCallbackQuery()->getData() == $this->getName()) {
            TelegramDb::updateStatus($callbackId, 'search-keyword');
            $this->getApi()->sendMessage($callbackId, $this->getDecription(), 'html');
        }
    }

    public function make($api, $data)
    {
        return parent::make($api, $data); // TODO: Change the autogenerated stub
    }
}