<?php
/**
 * Created by PhpStorm.
 * User: stosdima
 * Date: 20.12.17
 * Time: 3:46
 */

namespace TelegramNotifier\TelegramChain\CallbackqueryCommands;


use TelegramNotifier\Helper;
use TelegramNotifier\TelegramChain\Command;
use TelegramNotifier\TelegramDb;

class SearchByCategories extends Command
{
    protected $name = 'categories';

    protected $description;

    public function handle($data)
    {
        $helper = new Helper();
        $callbackId = $data->getCallbackQuery()->getMessage()->getChat()->getId();
        if ($data->getCallbackQuery()->getData() == $this->getName()) {
            if ($helper->get_categories_buttons_list()) {
                $keyboard = new \TelegramBot\Api\Types\Inline\InlineKeyboardMarkup($helper->get_categories_buttons_list());
                TelegramDb::updateStatus($callbackId, 'search-categories');
                $text = 'List of categories: ';
                $this->getApi()->sendMessage($callbackId, $text, null, false, null, $keyboard);
            } else {
                TelegramDb::resetStatus($callbackId);
                $text = 'At that moment you haven`t created categories ';
                $this->getApi()->sendMessage($callbackId, $text, null, false, null, null);
            }
        }
    }

    public function make($api, $data)
    {
        return parent::make($api, $data); // TODO: Change the autogenerated stub
    }
}