<?php
/**
 * Created by PhpStorm.
 * User: stosdima
 * Date: 20.12.17
 * Time: 5:02
 */

namespace TelegramNotifier\TelegramChain\CallbackqueryCommands;


use TelegramNotifier\TelegramChain\Command;
use TelegramNotifier\TelegramDb;

class Statistic extends Command
{
    protected $name = 'statistic';

    public function handle($data)
    {
        $callbackId = $data->getCallbackQuery()->getMessage()->getChat()->getId();
        if ($data->getCallbackQuery()->getData() == $this->getName()) {
            $allusers = count(TelegramDb::chatAll());
            $text = 'Current users: ' . $allusers;
            TelegramDb::resetStatus($callbackId);
            $this->getApi()->sendMessage($callbackId, $text);
        }
    }

    public function make($api, $data)
    {
        return parent::make($api, $data); // TODO: Change the autogenerated stub
    }
}